SchoolApp/Models/SchoolTask.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SchoolApp.Models
{
    public class SchoolTask
    {
        [Key]
        public int Id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string whichClas { get; set; }
        public bool IsNoted { get; set; }
        
    }
}

SchoolApp/Controllers/NotesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using SchoolApp.Models;

namespace SchoolApp.Controllers
{
    public class NotesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Notes
        public ActionResult Index()
        {
            return View(db.Notes.ToList()); // SELECT * FROM NOTES
        }

        // GET: Notes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Note note = db.Notes.Find(id);
            if (note == null)
            {
                return HttpNotFound();
            }
            return View(note);
        }

        // GET: Notes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Notes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,ForTask,WchitNote,email")] Note note)
        {
            if (ModelState.IsValid)
            {
                
                db.Notes.Add(note);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(note);
        }

        // GET: Notes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Note note = db.Notes.Find(id);
            if (note == null)
            {
                return HttpNotFound();
            }
            return View(note);
        }

        // POST: Notes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,ForTask,WchitNote,email")] Note note)
        {
            if (ModelState.IsValid)
            {
                db.Entry(note).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(note);
        }

        // GET: Notes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Note note = db.Notes.Find(id);
            if (note == null)
            {
                return HttpNotFound();
            }
            return View(note);
        }

        // POST: Notes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Note note = db.Notes.Find(id);
            db.Notes.Remove(note);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SchoolApp/Controllers/SchoolTasksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Runtime.InteropServices;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.Office.Interop.Excel;
using SchoolApp.Models;

namespace SchoolApp.Controllers
{
    public class SchoolTasksController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private Worksheet xlWorkSheet;

        // GET: SchoolTasks
        public ActionResult Index()
        {
            string currentTeacherId = User.Identity.GetUserId();
            ApplicationUser currentTeahcer = db.Users.FirstOrDefault(x => x.Id == currentTeacherId);
            return View(db.SchoolTasks.ToList().Where(x => x.whichClas == currentTeahcer.Clas));
        }

        public int[] countAVG(string title)
        {
            int avg = 0;
            int ct = 0;
            foreach (var item in db.Notes.ToArray().Where(x => x.ForTask == title))
            {
                if (item.WchitNote == "A")
                    avg += 5;
                if (item.WchitNote == "B")
                    avg += 4;
                if (item.WchitNote == "C")
                    avg += 3;
                if (item.WchitNote == "D")
                    avg += 2;
                if (item.WchitNote == "E")
                    avg += 1;
                ct++;
            }
            int[] retList = { avg, ct };
            return retList;
        }

        public ActionResult Generate()
        {
            string currentTeacherId = User.Identity.GetUserId();
            ApplicationUser currentTeahcer = db.Users.FirstOrDefault(x => x.Id == currentTeacherId);
            Microsoft.Office.Interop.Excel.Application xlApp = new Microsoft.Office.Interop.Excel.Application();
            Microsoft.Office.Interop.Excel.Workbook worKbooK;
            worKbooK = xlApp.Workbooks.Add(Type.Missing);
            xlWorkSheet = (Microsoft.Office.Interop.Excel.Worksheet)worKbooK.Worksheets.get_Item(1);
            xlWorkSheet.Cells[1, 1] = "Nazwa Zadania";
            xlWorkSheet.Cells[1, 2] = "Ile wystawionych ocen";
            xlWorkSheet.Cells[1, 3] = "Średnia ocena za zadanie:";


            int count = 2;
            foreach (SchoolTask item in (db.SchoolTasks.ToList().Where(x => x.whichClas == currentTeahcer.Clas)))
            {
                xlWorkSheet.Cells[count, 1] = item.title;
                int[] avgctlist = countAVG(item.title);
                xlWorkSheet.Cells[count, 2] = avgctlist[1];
                xlWorkSheet.Cells[count, 3] = avgctlist[0] / avgctlist[1];
                count++;


            }
            worKbooK.SaveAs("raport-" + DateTime.Now.ToString("yyyy-MM-dd") + ".xlsx");

            return RedirectToAction("Index");
        }

        public ActionResult GetMyStudents()
        {
            string currentTeacherId = User.Identity.GetUserId();
            ApplicationUser currentTeahcer = db.Users.FirstOrDefault(x => x.Id == currentTeacherId);
            return View(db.Users.ToList().Where(x => (x.Clas == currentTeahcer.Clas) && (x.Role.ToLower() == "student")));
        }
        public ActionResult AllNotes()
        {

            return View(db.Notes.ToList());
        }
        public ActionResult GetStudentNotes(string email)
        {

            return View(db.Notes.ToList().Where(x => x.email == email));
        }
        //get
        [HttpPost]
        public ActionResult UpdateNotes([Bind(Include = "Id,ForTask,WchitNote,email")] Note thisnote, string email, string note, string title)

        {
            thisnote.WchitNote = note;
            thisnote.email = email;
            thisnote.ForTask = title;
            db.Notes.Add(thisnote);
            db.SaveChanges();
            return RedirectToAction("NoteTask");

        }


        public ActionResult NoteTask(int? id, string title)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SchoolTask schoolTask = db.SchoolTasks.Find(id);
            if (schoolTask == null)
            {
                return HttpNotFound();
            }
            string currentTeacherId = User.Identity.GetUserId();
            ApplicationUser currentTeahcer = db.Users.FirstOrDefault(x => x.Id == currentTeacherId);
            ViewData["tytul"] = title;
            return View(db.Users.ToList().Where(x => x.Clas == currentTeahcer.Clas));
        }

        public ActionResult NoteThisTask(string email)
        {
            return View(email);
        }

        // GET: SchoolTasks/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SchoolTask schoolTask = db.SchoolTasks.Find(id);
            if (schoolTask == null)
            {
                return HttpNotFound();
            }
            return View(schoolTask);
        }

        // GET: SchoolTasks/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: SchoolTasks/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,title,description,whichClas")] SchoolTask schoolTask)
        {
            if (ModelState.IsValid)
            {
                string currentTeacherId = User.Identity.GetUserId();
                ApplicationUser currentTeahcer = db.Users.FirstOrDefault(x => x.Id == currentTeacherId);
                schoolTask.whichClas = currentTeahcer.Clas;
                db.SchoolTasks.Add(schoolTask);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(schoolTask);
        }

        public ActionResult Photoadd()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Photoadd(HttpPostedFileBase file)
        {
            string path = Server.MapPath("~/Images");
            string filename = Path.GetFileName(file.FileName);
            string currentTeacherId = User.Identity.GetUserId();
            ApplicationUser currentTeahcer = db.Users.FirstOrDefault(x => x.Id == currentTeacherId);
            string fn = currentTeahcer.kidMail.ToString();
            filename = fn.Substring(0,fn.IndexOf('@')) + ".jpg";
            string fullpath = Path.Combine(path, filename);
            file.SaveAs(fullpath);
            return RedirectToAction("Index","Home");
        }
        //[HttpPost]
        //[Route("uploader")]
        //public ActionResult Photoadd2(HttpPostedFileBase file)
        //{
           
            
        //        string filename = ContentDispositionHeaderValue.Parse(source.ContentDisposition).FileName.Trim('"');
        //        filename = this.EnsureCorrectFilename(filename); 
        //        var filenpath = this.GetPathAndFilename(filename);
        //        using (FileStream output = System.IO.File.Create(filenpath)) await source.CopyToAsync(output);
        //        var csv = GetCsvFromFile(filenpath);
        //        if (csv != null)
        //        { response = new JsonResult(csv); }
            
        //    return response;
        //}

        public ActionResult CheckKidNotes()
        {
            string currentParentId = User.Identity.GetUserId();
            ApplicationUser currentParent = db.Users.FirstOrDefault(x => x.Id == currentParentId);
            return View(db.Notes.ToList().Where(x => x.email == currentParent.kidMail));
        }

        // GET: SchoolTasks/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SchoolTask schoolTask = db.SchoolTasks.Find(id);
            if (schoolTask == null)
            {
                return HttpNotFound();
            }
            return View(schoolTask);
        }

        // POST: SchoolTasks/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,title,description,whichClass")] SchoolTask schoolTask)
        {
            if (ModelState.IsValid)
            {
                db.Entry(schoolTask).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(schoolTask);
        }

        // GET: SchoolTasks/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SchoolTask schoolTask = db.SchoolTasks.Find(id);
            if (schoolTask == null)
            {
                return HttpNotFound();
            }
            return View(schoolTask);
        }

        // POST: SchoolTasks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            SchoolTask schoolTask = db.SchoolTasks.Find(id);
            db.SchoolTasks.Remove(schoolTask);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SchoolApp/Views/SchoolTasks/AllNotes.cshtml
@model IEnumerable<SchoolApp.Models.Note>

@{
    ViewBag.Title = "All Notes";
}

<h2>AllNotes</h2>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ForTask)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.WchitNote)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.email)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ForTask)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.WchitNote)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.email)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit","Notes", new { id=item.Id }, null) 
        </td>
    </tr>
}

</table>

SchoolApp/Views/SchoolTasks/CheckKidNotes.cshtml
@model IEnumerable<SchoolApp.Models.Note>

@{
    ViewBag.Title = "CheckKidNotes";
}

<h2>All Notes had been given to your Child</h2>


<table class="table">
    <tr>
        <th>
            <p>Task</p>
        </th>
        <th>
            <p>Note</p>
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ForTask)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.WchitNote)
        </td>
       
        
    </tr>
}

</table>

SchoolApp/Views/SchoolTasks/Create.cshtml
@model SchoolApp.Models.SchoolTask

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>SchoolTask</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.whichClas, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.whichClas, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.whichClas, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SchoolApp/Views/SchoolTasks/Delete.cshtml
@model SchoolApp.Models.SchoolTask

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>SchoolTask</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.whichClas)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.whichClas)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SchoolApp/Views/SchoolTasks/Details.cshtml
@model SchoolApp.Models.SchoolTask

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>SchoolTask</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.whichClas)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.whichClas)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

SchoolApp/Views/SchoolTasks/Edit.cshtml
@model SchoolApp.Models.SchoolTask

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>SchoolTask</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.whichClas, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.whichClas, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.whichClas, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SchoolApp/Views/SchoolTasks/EditNote.cshtml
@model SchoolApp.Models.Note

@{
    ViewBag.Title = "EditNote";
}

<h2>Zmień ocenę</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Note</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.ForTask, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ForTask, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ForTask, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SchoolApp/Views/SchoolTasks/GetMyStudents.cshtml
@model IEnumerable<SchoolApp.Models.ApplicationUser>

@{
    ViewBag.Title = "GetMyStudents";
}

<h2>GetMyStudents</h2>



<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
    </tr>p

    @foreach (var item in Model)
    {
        <tr>
            <td>
                <a href="@Url.Action("GetStudentNotes", "SchoolTasks", new { email=item.Email})">@Html.DisplayFor(modelItem => item.Email)</a>
            </td>
           
        </tr>
    }

</table>

SchoolApp/Views/SchoolTasks/GetStudentNotes.cshtml
@model IEnumerable<SchoolApp.Models.Note>

@{
    ViewBag.Title = "GetStudentNotes";
}

<h2>Oceny Studenta</h2>



<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ForTask)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.WchitNote)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ForTask)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.WchitNote)
            </td>
        </tr>
    }

</table>

SchoolApp/Views/SchoolTasks/Index.cshtml
@model IEnumerable<SchoolApp.Models.SchoolTask>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.whichClas)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.whichClas)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })|
                @Html.ActionLink("Note", "NoteTask", new { id = item.Id, title = item.title })
            </td>
        </tr>
    }

</table>
    

SchoolApp/Views/SchoolTasks/NoteTask.cshtml
@model IEnumerable<SchoolApp.Models.ApplicationUser>

@{
    ViewBag.Title = "Note Task";
}

<h2>Oceń Zadanie</h2>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>


        <th></th>
    </tr>
    @foreach (var item in Model.Where(x => x.Role == "Student"))
    {

        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DropDownList("Ocena", new SelectList(new List<String>() { "A", "B", "C", "D", "E" }), new { id = item.Email })
            </td>

            <td>
                <button style="font-size: 16px;background: whitesmoke;" type="button" onclick="AddGrade('@item.Email', '@ViewData["tytul"]')">Dodaj ocenę</button>
            </td>
            
        </tr>

    }



</table>
<script>
    function AddGrade(email,title) {


            var note = document.getElementById(email).value;
            alert(note);
            $.ajax({
                type: "POST",
                url: '/SchoolTasks/UpdateNotes',
                data:{
                    email: email,
                    note: note,
                    title: title
                },
                beforeSend: function () {
                },
                success: function (response) {
                    alert("Ocena została dodana")
                },
                error: function (err) {
                    alert(err.stackTrace);
                }
                
            });

        }
</script>

<div>
    @Html.ActionLink("Back to List", "Index")
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")


}

SchoolApp/Views/SchoolTasks/NoteThisTask.cshtml
@model SchoolApp.Models.ApplicationUser

@{
    ViewBag.Title = "Note Task";
}

<h2>Oceń Zadanie ucznia</h2>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            <p>Ocena</p>
        </th>


        <th></th>
    </tr>
    

        <tr>
            <td>
                @Html.LabelFor(model => model.Notes, htmlAttributes: new { @class = "control-label col-md-2" })
            </td>

            <td>

                @Html.ActionLink("Wystaw Ocenę", "UpdateNotes", new { email = Model.Email, note = Model.Notes})
            </td>
        </tr>

    


</table>

<div>
    @Html.ActionLink("Back to List", "Index")
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SchoolApp/Views/SchoolTasks/Photoadd.cshtml
@{
    ViewBag.Title = "Add Your Kid Photo";
}

<h2>Add Your Kid Photo</h2>

<div class="row">
    <div class="col-md-10">
        @using (Html.BeginForm("Photoadd","SchoolTasks", FormMethod.Post, new {@enctype = "multipart/form-data" }))
        {
        <input type="file" name="file"/>
        <br />
        <input type="submit" value="Upload" />
        }
    </div>
</div>

SchoolApp/Views/SchoolTasks/_TaskList.cshtml
@model IEnumerable<SchoolApp.Models.SchoolTask>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.whichClas)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.whichClas)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>